# Structure:
#   - One season = WEEKS_PER_SEASON weeks, repeating the same template.
#   - Difficulty scales each season via a per-season multiplier.
#   - MAX_SEASONS caps how long the game runs (set to -1 for infinite).
#
# NOTE: opponent_traits and situations are NOT generated here.
# They are generated by GameManager using TraitMatchup, to avoid
# circular dependency issues at parse time.

class_name Calendar
extends RefCounted

const WEEKS_PER_SEASON: int = 24   # weeks in one full season
const MAX_SEASONS:      int = 10   # -1 = infinite
const SEASON_DIFFICULTY_STEP: float = 0.08

const TYPE_NORMAL:     String = "normal"
const TYPE_IMPORTANT:  String = "important"
const TYPE_TOURNAMENT: String = "tournament"
const TYPE_SOLO:       String = "solo"

const OPPONENT_NAMES: Array[String] = [
	"Phantom Edge",     # 1  — top tier
	"Neon Siege",       # 2
	"Axiom Prime",      # 3
	"Zero Hour",        # 4
	"Orbital Strike",   # 5
	"Void Protocol",    # 6
	"Iron Circuit",     # 7
	"Shadow Codec",     # 8
	"Static Surge",     # 9
	"Null Vector",      # 10
	"Apex Protocol",    # 11
	"Binary Storm",     # 12
	"Frost Signal",     # 13
	"Echo Breach",      # 14
	"Copper Reflex",    # 15
	"Delta Lag",        # 16
	"Slow Queue",       # 17
	"Packet Drop",      # 18
	"Bronze Timeout",   # 19
	"Last Ping",        # 20  — bottom tier
]

const LABEL_TO_POSITION: Dictionary = {
	"dominant": [1,  5],
	"strong":   [6,  10],
	"average":  [11, 15],
	"weak":     [16, 20],
}

const WEEK_TEMPLATE: Array = [
	# Block 1 — Early grind
	{ "type": TYPE_NORMAL,     "opponent":  84, "label": "weak"     },  #  1
	{ "type": TYPE_SOLO,       "opponent":  87, "label": "weak"     },  #  2 ★solo
	{ "type": TYPE_NORMAL,     "opponent":  92, "label": "weak"     },  #  3
	{ "type": TYPE_IMPORTANT,  "opponent":  97, "label": "average"  },  #  4 ★
	{ "type": TYPE_NORMAL,     "opponent":  93, "label": "average"  },  #  5
	{ "type": TYPE_SOLO,       "opponent":  96, "label": "average"  },  #  6 ★solo

	# Block 2 — Mid-season
	{ "type": TYPE_NORMAL,     "opponent":  99, "label": "average"  },  #  7
	{ "type": TYPE_NORMAL,     "opponent": 102, "label": "average"  },  #  8
	{ "type": TYPE_IMPORTANT,  "opponent": 107, "label": "strong"   },  #  9 ★
	{ "type": TYPE_SOLO,       "opponent": 103, "label": "strong"   },  # 10 ★solo
	{ "type": TYPE_NORMAL,     "opponent": 106, "label": "strong"   },  # 11
	{ "type": TYPE_TOURNAMENT, "opponent": 119, "label": "dominant" },  # 12 🏆

	# Block 3 — Late season
	{ "type": TYPE_NORMAL,     "opponent": 107, "label": "strong"   },  # 13
	{ "type": TYPE_NORMAL,     "opponent": 110, "label": "strong"   },  # 14
	{ "type": TYPE_IMPORTANT,  "opponent": 116, "label": "dominant" },  # 15 ★
	{ "type": TYPE_SOLO,       "opponent": 111, "label": "strong"   },  # 16 ★solo
	{ "type": TYPE_NORMAL,     "opponent": 115, "label": "dominant" },  # 17
	{ "type": TYPE_IMPORTANT,  "opponent": 121, "label": "dominant" },  # 18 ★

	# Block 4 — Season finale
	{ "type": TYPE_NORMAL,     "opponent": 116, "label": "dominant" },  # 19
	{ "type": TYPE_NORMAL,     "opponent": 119, "label": "dominant" },  # 20
	{ "type": TYPE_IMPORTANT,  "opponent": 125, "label": "dominant" },  # 21 ★
	{ "type": TYPE_NORMAL,     "opponent": 121, "label": "dominant" },  # 22
	{ "type": TYPE_TOURNAMENT, "opponent": 131, "label": "dominant" },  # 23 🏆
	{ "type": TYPE_TOURNAMENT, "opponent": 136, "label": "dominant" },  # 24 🏆🏆
]


# Returns the base calendar entry for a given absolute week number (1-based).
# Scales opponent score by season. Does NOT include opponent_name, opponent_traits,
# or situations — those are added by GameManager which has access to TraitMatchup.
static func get_week(absolute_week: int) -> Dictionary:
	var season:         int = get_season(absolute_week)
	var week_in_season: int = get_week_in_season(absolute_week)
	var template_idx:   int = clamp(week_in_season - 1, 0, WEEK_TEMPLATE.size() - 1)
	var template:       Dictionary = WEEK_TEMPLATE[template_idx].duplicate()
	var scale: float = 1.0 + SEASON_DIFFICULTY_STEP * (season - 1)
	
	template["opponent"]       = int(template["opponent"] * scale)
	template["season"]         = season
	template["week_in_season"] = week_in_season

	return template


static func get_opponent_name(season: int, week_in_season: int, difficulty_label: String) -> String:
	var name_seed: int = season * 500 + week_in_season * 17 + 3
	seed(name_seed)
	
	var pos_range: Array = LABEL_TO_POSITION.get(difficulty_label, [11, 15])
	var pos_min: int = pos_range[0] - 1
	var pos_max: int = pos_range[1] - 1
	var name_idx: int = pos_min + (randi() % (pos_max - pos_min + 1))
	
	return OPPONENT_NAMES[clamp(name_idx, 0, OPPONENT_NAMES.size() - 1)]


static func get_season(absolute_week: int) -> int:
	return int((absolute_week - 1) / WEEKS_PER_SEASON) + 1


static func get_week_in_season(absolute_week: int) -> int:
	return ((absolute_week - 1) % WEEKS_PER_SEASON) + 1


static func is_game_over(absolute_week: int) -> bool:
	if MAX_SEASONS == -1:
		return false
		
	return get_season(absolute_week) > MAX_SEASONS


static func get_next_event(absolute_week: int) -> Dictionary:
	var current_idx: int = get_week_in_season(absolute_week) - 1

	for i in range(current_idx + 1, WEEK_TEMPLATE.size()):
		var entry: Dictionary = WEEK_TEMPLATE[i]
		
		if entry["type"] != TYPE_NORMAL:
			return {
				"type":       entry["type"],
				"weeks_away": i - current_idx,
			}

	return {}
